### ISSUE TITLE
comma "," needed after each line in object

### ISSUE THREAD

**Issue by alieudev** [learn-co-curriculum/phase-1-array-iterator-methods#1]
Under Why Use JavaScript's Iterator Methods?, the array users has some missing commas after the last object in each of the arrays from users[1:] . In other words favoriteAnimal isn't closed with a comma after it has been given a value. 

'''
{
    firstName: 'Tracy',
    lastName: 'Lum',
    favoriteColor: 'Yellow',
    favoriteAnimal: 'Penguin'
    personalQuote: "I just got lost in thought - it was unfamiliar territory"
  },

'''

**Comment by graciemcguire** [comment]
Hey @alieudev we've fixed this issue, thanks for flagging!
