### ISSUE TITLE
Order of instruction for Arrays, Objects, and Array Iteration

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/phase-1-array-iterator-methods#4]
### Canvas Link

https://learning.flatironschool.com/courses/5185/pages/array-iterator-methods?module_item_id=396136

### Concern

Hello! This is a piece of general feedback regarding the order in which material is presented to students. It pertains to the order in which Arrays, Objects, and Array Iteration are taught to students - this order differs from the way these topics are laid out on Canvas. I know this falls outside of the usual types of issues that are discussed here, but I wanted to make sure I passed this feedback along, as I think it's important. If this is an inquiry that would be better directed at the central lecture team, please let me know! 

### Additional Context

Central Model Wiki layout for Phase 1: https://github.com/learn-co-curriculum/central-model-wiki/blob/main/Phase%201/week-1.md

### Suggested Changes

I have some feedback about the ordering of certain concepts for Phase 1 Week 1 that I'd like to pass along. This current order is different than the chronological order laid out in Canvas (which I think makes more sense). If this inquiry is better directed at Central Lecture, please let me know!

We're currently teaching Array Iteration before we teach Objects, both in lecture and in homework / labs. The current split is Day 3, Arrays and Array Iteration, and Day 4, Objects. While this make sense on a topical level, I think it would be a lot more beneficial to students to teach Data Structures in JavaScript as a whole (both Arrays and Objects) before teaching Array Iteration, which is the way it's currently laid out on Canvas. I can think of a few reasons for making this change.

- **The Array Iteration section requires a working knowledge of Objects:**

- The .find() lab requires students to access key value pairs within Objects in order to pass the tests. The .filter() lab also requires a knowledge of Objects.
- Most of the labs / reading use Objects in examples when demonstrating key concepts for iteration.
- Being unfamiliar with Objects will trip students up even further as they try to get through Iteration methods, which are definitely some of the most complex concepts they'll be working with in Phase 1.

- **Students will have more time to get familiar with Looping, Iteration, and Callback Functions.**

- Both Looping and Iteration are brought up in the "Working With Data Structures" section, part way through the portion devoted to Objects.
- > Specifically, the "Looping Lab" and "Object Iteration" sections. 
- > The "Object Iteration" section also talks about Array Iteration - "for of" loops - which is an essential concept for understanding Iteration Methods. 
- > This concept isn't discussed in any of the "Array" specific sections or in the Looping Lab section. 
- > It is discussed in the "JavaScript Loops" video, but this isn't assigned until after we cover Array Iteration: https://github.com/learn-co-curriculum/central-model-wiki/blob/main/Phase%201/week-1.md.
- Having a solid grasp of how Looping and Iteration works is essential to understanding how Iteration Methods work. It could be highly beneficial for students to have a night of sleep in between learning about Looping and Iteration and trying to implement them in a more complex manner via Iteration Methods.
- The same applies to Callback Functions. Students will have learned about Callback Functions a day or two prior, but it will still give them more time to digest what they are and how they work before they're asked to use them in conjunction with Iteration.

- **Array Iteration is hard.**
- The Array Iteration labs are by far the most conceptually challenging labs of Phase 1, and are very time consuming.
- Allowing a full day devoted to Array Iteration could help students feel less rushed to get through the material, and could prevent them from falling behind.
- Doing Data Structures in a single day followed by Array Iteration in a single day seems like a more feasible approach that would give students a more measured, manageable workload.
- It feels like a more appropriate scaling of difficulty to discuss Data Structures, Looping, and Iteration before talking about Array Iteration methods. Presenting the material in this manner would stack concepts on top of each other in terms of complexity, instead of backfilling more basic concepts after diving into more difficult material.

- **Minimizing student stress.**
- Because students are moving at such a fast pace, it seems best to try to minimize the amount of unnecessary stress we impart upon them, especially during week one.
- The manner in which the material is currently presented feels out of order and needlessly stressful (I remember this feeling when I was a student - many of my cohort mates at the time voiced similar feelings).
- Reorganizing the curriculum in this manner wouldn't reduce the difficulty of the material in any way, but it could present material to students in a way that mitigates stress and feels more natural and streamlined.

I remember this current curriculum layout as being the biggest negative aspect of my own student experience at Flatiron, and a source of panic and despair for a lot of students who were thrown off by the abrupt difficulty spike. I understand that making this kind of change isn't something that happens overnight, but I hope you consider it as an alternative to the current layout. It could prevent students from floundering, giving them more bandwidth to learn about other material that would prove invaluable to them later down the road.

Thanks for taking the time to read this! I hope it's helpful. I'd be happy to talk in person with somebody about this if anybody is interested.

Best,

Matt

**Comment by lizbur10** [comment]
Hi Matt - sorry for taking so long to respond. 

Thanks so much for taking the time to put this together - your very thoughtful feedback on this is much appreciated!

The issues with Phase 1 are very much on the radar screen. We have a bandwidth issue right now, but we will address it as soon as we are able. 💙

**Comment by Matt-Eva** [comment]
Hi Liz,

No problem, thank you for getting back to me! I imagine you must all be
swamped with the whole Python curriculum rollout / everything else that
goes on at Flatiron. Please let me know if there's anything I can do to
help! Always happy to contribute feedback when applicable.

Best,

Matt

**Comment by lizbur10** [comment]
@jlboba some feedback for when we overhaul Phase 1

**Comment by Matt-Eva** [comment]
No longer an issue! Phase 1 being re-written.
